from .province import ProvinceSerializer
from .district import DistrictSerializer
from .ward import WardSerializer
from .shipping_address import ShippingAddressSerializer
from .customer_short import CustomerShortSerializer
from .customer import CustomerSerializer
from .product_category import ProductCategorySerializer
from .promotion import PromotionSerializer
from .product import ProductSerializer
from .product_short import ProductShortSerializer
from .product_image import ProductImageSerializer
from .cart import CartSerializer
from .order import OrderSerializer
