# Generated by Django 5.0.4 on 2025-08-03 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='ecommerce.customer'),
        ),
        migrations.AddField(
            model_name='districtmapping',
            name='delivery_service_provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_maping', to='ecommerce.deliveryserviceprovider'),
        ),
        migrations.AddField(
            model_name='districtmapping',
            name='district',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_maping', to='ecommerce.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='mapping',
            field=models.ManyToManyField(blank=True, null=True, related_name='districts', through='ecommerce.DistrictMapping', to='ecommerce.deliveryserviceprovider'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_descriptions', to='contents.longcontent'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_names', to='contents.shortcontent'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='contents.shortcontent'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_names', to='contents.shortcontent'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='ecommerce.productcategory'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='promotionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='promotionitem',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='ecommerce.promotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='promotions', through='ecommerce.PromotionItem', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='ecommerce.province'),
        ),
        migrations.AddField(
            model_name='provincemapping',
            name='delivery_service_provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_maping', to='ecommerce.deliveryserviceprovider'),
        ),
        migrations.AddField(
            model_name='provincemapping',
            name='province',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='maping', to='ecommerce.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='mapping',
            field=models.ManyToManyField(blank=True, null=True, related_name='provinces', through='ecommerce.ProvinceMapping', to='ecommerce.deliveryserviceprovider'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.customer'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.district'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.province'),
        ),
        migrations.AddField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='ecommerce.district'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.ward'),
        ),
        migrations.AddField(
            model_name='wardmapping',
            name='delivery_service_provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_maping', to='ecommerce.deliveryserviceprovider'),
        ),
        migrations.AddField(
            model_name='wardmapping',
            name='ward',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_maping', to='ecommerce.ward'),
        ),
        migrations.AddField(
            model_name='ward',
            name='mapping',
            field=models.ManyToManyField(blank=True, null=True, related_name='wards', through='ecommerce.WardMapping', to='ecommerce.deliveryserviceprovider'),
        ),
    ]
