# Generated by Django 5.0.4 on 2025-09-20 08:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('vip', 'VIP')], max_length=10)),
            ],
            options={
                'db_table': 'hr_customer',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price_per_m2', models.IntegerField()),
                ('cleaning_rate_m2_per_h', models.IntegerField()),
            ],
            options={
                'db_table': 'hr_service_type',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hr_skill',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preferred_start_time', models.DateTimeField()),
                ('preferred_end_time', models.DateTimeField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.customer')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.servicetype')),
            ],
            options={
                'db_table': 'hr_order',
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workload_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.order')),
            ],
            options={
                'db_table': 'hr_decision_log',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.order')),
            ],
            options={
                'db_table': 'hr_assignment',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.skill')),
            ],
            options={
                'db_table': 'hr_employee_skill',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
