# Generated by Django 5.0.4 on 2025-09-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_confirm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
