# Generated by Django 5.0.4 on 2025-09-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_order_cost_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(choices=[('Hải Châu', 'Hải Châu'), ('Ngũ Hành Sơn', 'Ngũ Hành Sơn'), ('Liên Chiểu', 'Liên Chiểu'), ('Sơn Trà', 'Sơn Trà'), ('Cẩm Lệ', 'Cẩm Lệ'), ('Thanh Khê', 'Thanh Khê')], max_length=20),
        ),
    ]
