# Generated by Django 5.0.4 on 2025-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_customer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_log',
            field=models.TextField(blank=True, help_text='Ghi chú của admin về đơn hàng', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_feedback',
            field=models.TextField(blank=True, help_text='Phản hồi của khách hàng sau khi hoàn thành dịch vụ', null=True),
        ),
    ]
