# Generated by Django 5.0.4 on 2025-08-03 04:06

import django.db.models.deletion
import django.utils.timezone
import uuid
import websites.models.article
import websites.models.build
import websites.models.site
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'websites_sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_category_names', to='contents.shortcontent')),
            ],
            options={
                'db_table': 'websites_article_categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=250)),
                ('keywords', models.CharField(blank=True, max_length=250)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to=websites.models.article.article_thumbnail_path)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published'), (2, 'Un-published')], default=0)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_contents', to='contents.longcontent')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_descriptions', to='contents.shortcontent')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_titles', to='contents.shortcontent')),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='articles', to='websites.articlecategory')),
            ],
            options={
                'db_table': 'websites_articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.article')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.section')),
            ],
            options={
                'db_table': 'websites_section_acticles',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='sections', through='websites.SectionArticle', to='websites.article'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.FileField(blank=True, max_length=255, null=True, upload_to=websites.models.site.website_icon_path)),
                ('template', models.FileField(blank=True, max_length=255, null=True, upload_to=websites.models.site.website_template_path)),
                ('template_settings', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published'), (2, 'Un-published')], default=0)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_descriptions', to='contents.shortcontent')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_titles', to='contents.shortcontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='websites.site'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=250)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published'), (2, 'Un-published')], default=0)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_contents', to='contents.longcontent')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_descriptions', to='contents.shortcontent')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_titles', to='contents.shortcontent')),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='websites.site')),
            ],
            options={
                'db_table': 'websites_routes',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='websites.menu')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_menu_titles', to='contents.shortcontent')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='websites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.FileField(blank=True, max_length=255, null=True, upload_to=websites.models.build.website_archive_path)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Open'), (1, 'Scheduling'), (2, 'In-progress'), (3, 'Processed'), (4, 'Deployed'), (5, 'Failed')], default=0)),
                ('info', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='websites.site')),
            ],
            options={
                'db_table': 'websites_builds',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sites',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='websites.site'),
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['slug'], name='websites_ar_slug_7ea674_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name'], name='websites_se_name_94aaa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('site', 'name')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['path'], name='websites_ro_path_629ddf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('site', 'path')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='websites_ar_slug_32cc9d_idx'),
        ),
    ]
