# Generated by Django 5.0.4 on 2025-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='area',
            field=models.CharField(blank=True, help_text='Khu vực làm việc của nhân viên', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='completed_orders_count',
            field=models.PositiveIntegerField(default=0, help_text='Số lượng đơn hàng đã hoàn thành'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mức lương', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tổng số giờ làm việc', max_digits=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_end_time',
            field=models.TimeField(blank=True, help_text='Giờ kết thúc làm việc', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_start_time',
            field=models.TimeField(blank=True, help_text='Giờ bắt đầu làm việc', null=True),
        ),
    ]
