# Generated by Django 5.0.4 on 2025-09-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_employee_area_employee_completed_orders_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'No working hours set'), (1, 'Active - Working Hours'), (2, 'Inactive - Outside Working Hours')], default=0, help_text='Auto-computed working status based on working hours and current time'),
        ),
    ]
