# Generated by Django 5.0.4 on 2025-09-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'No working hours set'), (1, 'Active'), (2, 'Inactive')], default=0, help_text='Auto-computed working status based on working hours and current time'),
        ),
    ]
